server:
  port: 9004
  context-path: /sms

  devtools:
    restart:
      enabled: true

spring:
  activemq:            #需要先安装 activemq:  http://blog.csdn.net/liuchuanhong1/article/details/52057711     http://blog.csdn.net/liuchuanhong1/article/details/54603546
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: true
    pool:
      enbaled: false

